---
- name: "Install the correct version x64-x86"
  include: "dante_make.yml"
  when: ansible_machine == "x86_64"

- name: "Install the correct version ARM"
  include: "dante_apt.yml"
  when: ansible_machine == "aarch64"
